### PR TITLE
fix: add `cleavr` to built-in presets

### LINKED ISSUE #600: Nitro entry missing for the cleavr preset
Running the build command `NITRO_PRESET=cleavr npm run build --production` we're encountering an error with the following message:

 `ERROR  Nitro entry is missing! Is "cleavr" preset correct?` 

Please check the gist file for the full log https://gist.github.com/anishghimire862/9bc8964aecad9d26dc0ab3fdb9b7ebe2

This must be due to the missing entries. We added the preset but somehow forgot about the entries.

### PR DESCRIPTION
**Pull request by anishghimire862**
### 🔗 Linked issue

#600

### ❓ Type of change

- [x] 📖 Documentation (updates to the documentation or readme)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [x] 👌 Enhancement (improving an existing functionality like performance)
- [x] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

Add missing entry for Cleavr

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [x] I have updated the documentation accordingly.

Resolves #600

### CODE REVIEW

File: src/presets/cleavr.ts [hunk 1]
```diff
@@ -1,5 +1,6 @@
 import { defineNitroPreset } from '../preset'
 
 export const cleavr = defineNitroPreset({
+  entry: '#internal/nitro/entries/cleavr',
```
Comment (danielroe) [inline src/presets/cleavr.ts:4]: it doesn't need to have its own entry; by default it will use the node server entry.

I think the issue you encountered was due to a regression in the build pipeline: https://github.com/nuxt/framework/issues/8213#issuecomment-1279786434

**Comment by pi0** [comment]
https://github.com/unjs/nitro/issues/600#issuecomment-1284209146

**Review by pi0 — APPROVED** [review]
