### PR TITLE
fix(options): set `scheduledTasks` to an empty object by default

### LINKED ISSUE #2283: Scheduled tasks type on nitro options are incorrect
### Environment

Nitro 2.9

### Reproduction

— (I'll do the PR)

### Describe the bug

https://github.com/unjs/nitro/blob/8a62e7dbaeeffb6dff533c7000aba51a5c85e479/src/types/nitro.ts#L342

The types are incorrect, it should be 

```ts
 scheduledTasks?:  { [cron: string]: string[] }; 
```

I think maybe of having to handle the undefined case when we have no scheduled tasks, we could just make this property be an empty object as default (as it's assignable).

### Additional context

_No response_

### Logs

_No response_

### PR DESCRIPTION
**Pull request by noook**
### 🔗 Linked issue

Fixes #2283, related to https://github.com/nuxt/devtools/pull/626

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation, readme, or JSdoc annotations)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

Nitro config types indicate that `nitro.options.scheduledTasks` should always be an object, empty or not.  This PR makes the property an empty object as default as opposed to `undefined` which is not assignable to
```ts
scheduledTasks: { [cron: string]: string | string[] }
```

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

File: src/nitro.ts [hunk 1]
```diff
@@ -126,7 +126,7 @@ export async function createNitro(
 
   // Virtual module for tasks (TODO: Move to rollup plugin)
   nitro.options.virtual["#internal/nitro/virtual/tasks"] = () => {
-    const _scheduledTasks = Object.entries(nitro.options.scheduledTasks || {})
+    const _scheduledTasks = Object.entries(nitro.options.scheduledTasks)
```
Comment (pi0) [inline src/nitro.ts:129]: there is no harm to have extra runtime safety :) 

```suggestion
    const _scheduledTasks = Object.entries(nitro.options.scheduledTasks || {})
```

**Review by pi0 — APPROVED** [review]
