### PR TITLE
fix(externals): compare package paths against normalized `id`

### LINKED ISSUE #2367: externals comparison mismatch on windows
### Environment

Rather big Nuxt 3 SSR application with over 50 nuxt modules, tens of pages, tens of components (many async), majority imported from multiple npm dependencies. Nuxt build generates around 800 .mjs files.
nuxt@3.10.3, nitropack@2.9.6, rollup@4.14.1, Windows 10.

### Reproduction

Unfortunately repo is private and it will be very time consuming to recreate dummy app with similar amount of files and deps, hopefully info below will be useful enough.

### Describe the bug

Our nuxt 3 app Nitro server prod build `Building Nuxt Nitro server (preset: node-server)"` finishes in 5min on Linux machines but builds for up to 1h on Windows (tried on multiple pcs). CPU and RAM are not maxed out.  Rollup plugin `resolveId` is called 60K times. 

Lengthy investigation and debugging have shown that Nitro/Rollup "node-externals" plugin is the culprit.
One of likely reasons is that resolved `packageEntry` and `originalId` on [this line](https://github.com/unjs/nitro/blob/main/src/rollup/plugins/externals.ts#L168) absolute urls have different path structures (`C:/.../`  vs `C:\...\`) which incorrectly leads to additional module resolution with incorrect module id (e.g. `node-fetch-3/` (trailing slash)) which always misses [resolve cache](https://github.com/unjs/nitro/blob/main/src/rollup/plugins/externals.ts#L47). 

Screenshot below with actual values from debugger:
Screenshot_325

Quick fix of normalizing path [here](https://github.com/unjs/nitro/blob/main/src/rollup/plugins/externals.ts#L168) `&& packageEntry.replaceAll('/', '\\') !== originalId` brings down build time to ~17min. Better, but still slow.

Enabling [legacyExternals](https://nitro.unjs.io/config#legacyexternals) brings down build to 2min, but requires additional config changes (created separate issue focusing on perf difference https://github.com/unjs/nitro/issues/2369 )

### Additional context

_No response_

### Logs

```sh
Rollup timings, majority of 52min build is spent on generating module graph, plugin timings are not helpful:

{
  '# BUILD': [ 3171467.7106000185, -76545200, 887349800 ],
  '## initialize': [ 3.4800000190734863, 242648, 964142200 ],
  '- plugin 2 (unimport) - buildStart': [ 1.7156999707221985, 193752, 964100096 ],
  '- plugin 5 (replace) - buildStart': [ 0.018299996852874756, 752, 964102176 ],
  '- plugin 16 (alias) - buildStart': [ 0.13370001316070557, 2448, 964105288 ],
  '- plugin 18 (node-resolve) - buildStart': [ 0.4077000021934509, 10648, 964116864 ],
  '- plugin 19 (commonjs) - buildStart': [ 0.7057999968528748, 18512, 964135960 ],
  '## generate module graph': [ 3164256.943300009, -122423984, 841719120 ],
  '- plugin 0 (commonjs--resolver) - resolveId': [ 336.0958986878395, 7821904, 1574785856 ],
  '- plugin 1 (nuxt:import-protection) - resolveId': [ 1225.359995007515, 4232600, 1574790328 ],
  '- plugin 3 (raw) - resolveId': [ 285.7907053232193, 14111264, 1574793088 ],
  '- plugin 7 (dynamic-require) - resolveId': [ 123.35879743099213, 12355024, 1574794632 ],
  '- plugin 8 (virtual) - resolveId': [ 802.3412969708443, 174571112, 1574800072 ],
  '- plugin 9 (virtual) - resolveId': [ 751.0079011917114, 8665584, 1574805512 ],
  '- plugin 10 (virtual) - resolveId': [ 745.5792000889778, 53840128, 1574810968 ],
  '- plugin 11 (virtual) - resolveId': [ 707.5736020207405, 56273928, 1574816440 ],
  '- plugin 12 (virtual) - resolveId': [ 716.2702045440674, 11479696, 1574821896 ],
  '- plugin 13 (virtual) - resolveId': [ 695.4516054391861, -11236760, 1574827352 ],
  '- plugin 14 (virtual) - resolveId': [ 698.5780059099197, 31439744, 1574832808 ],
  '- plugin 15 (virtual) - resolveId': [ 695.3984983563423, 21370552, 1574838264 ],
  '- plugin 16 (alias) - resolveId': [ 279.47429895401, 68180472, 1574840872 ],
  '- plugin 17 (node-externals) - resolveId': [ 2361.8438099622726, -255946104, 1574852336 ],
  '- plugin 22 (spy) - resolveId': [ 2960.567001760006, 25590968, 1580515568 ],
  '- plugin 18 (node-resolve) - resolveId': [ 564.281893491745, -33429552, 1580517144 ],
  '- plugin 3 (raw) - load': [ 7.130301237106323, 277776, 1569173640 ],
  '- plugin 7 (dynamic-require) - load': [ 6.710099399089813, 690008, 1569178576 ],
  '- plugin 8 (virtual) - load': [ 6.607400417327881, 741088, 1569183072 ],
  '- plugin 9 (virtual) - load': [ 5.544400751590729, 729064, 1569191816 ],
  '- plugin 10 (virtual) - load': [ 3.7262999415397644, 737192, 1569197352 ],
  '- plugin 11 (virtual) - load': [ 4.633598625659943, 712072, 1569201512 ],
  '- plugin 12 (virtual) - load': [ 6.239498555660248, 844232, 1569206320 ],
  '- plugin 13 (virtual) - load': [ 3.1917991638183594, 714208, 1569210856 ],
  '- plugin 14 (virtual) - load': [ 5.202499866485596, 863032, 1569215376 ],
  '- plugin 15 (virtual) - load': [ 3.5597003698349, 706408, 1569248624 ],
  '- plugin 18 (node-resolve) - load': [ 4.555399954319, 319832, 1569307616 ],
  '- plugin 19 (commonjs) - load': [ 7.04049950838089, 313304, 1569312568 ],
  '- plugin 2 (unimport) - transform': [ 401.0567016005516, 32252744, 1569177296 ],
  '- plugin 3 (raw) - transform': [ 6.153501331806183, 299888, 1569181776 ],
  '- plugin 5 (replace) - transform': [ 296.33579981327057, 48628984, 1569190520 ],
  '- plugin 6 (esbuild) - transform': [ 212.13729989528656, 11070112, 1569195744 ],
  '- plugin 7 (dynamic-require) - transform': [ 19.062299966812134, 1629952, 1569202376 ],
  '- plugin 19 (commonjs) - transform': [ 950.1781006455421, -58025480, 1569206912 ],
  '- plugin 20 (json) - transform': [ 6.771701335906982, 1076776, 1569211432 ],
  '- plugin 21 (inject) - transform': [ 2607.5473991036415, 363718520, 1569246416 ],
  'generate ast': [ 2805.7548992037773, 737931136, 1569272432 ],
  '## sort and bind modules': [ 226.63739997148514, 72232048, 913951232 ],
  '## mark included statements': [ 3377.0198000073433, -134081552, 779869744 ],
  'treeshaking pass 1': [ 3.76419997215271, 495936, 914449216 ],
  'treeshaking pass 2': [ 5.288699984550476, 2277408, 916726688 ],
  'treeshaking pass 3': [ 12.635300040245056, -9734768, 906991984 ],
  'treeshaking pass 4': [ 10.63100004196167, 4190704, 911182752 ],
  'treeshaking pass 5': [ 14.535799980163574, 6648496, 917831312 ],
  'treeshaking pass 6': [ 38.45750004053116, 2491136, 920322512 ],
  'treeshaking pass 7': [ 30.63459998369217, -2531848, 917791808 ],
  'treeshaking pass 8': [ 28.82200002670288, -5566400, 912225472 ],
  'treeshaking pass 9': [ 63.18519997596741, 13240936, 925466472 ],
  'treeshaking pass 10': [ 266.26839995384216, 19100416, 944566952 ],
  'treeshaking pass 11': [ 565.0429000258446, -188306960, 756260056 ],
  'treeshaking pass 12': [ 365.69069999456406, 4865416, 761125560 ],
  'treeshaking pass 13': [ 210.54399996995926, 15550368, 776675992 ],
  'treeshaking pass 14': [ 142.9780000448227, 5809640, 782485696 ],
  'treeshaking pass 15': [ 142.46189999580383, 3041984, 785527744 ],
  'treeshaking pass 16': [ 184.08860003948212, -2191448, 783336360 ],
  'treeshaking pass 17': [ 182.14230000972748, 627080, 783963504 ],
  'treeshaking pass 18': [ 145.85959994792938, 30712, 783994280 ],
  'treeshaking pass 19': [ 125.89139997959137, 8873896, 792868240 ],
  'treeshaking pass 20': [ 125.59810000658035, -8392256, 784476048 ],
  'treeshaking pass 21': [ 125.62040001153946, -3521256, 780954856 ],
  'treeshaking pass 22': [ 117.37769997119904, 4581200, 785536120 ],
  'treeshaking pass 23': [ 116.16970002651215, 3373960, 788910144 ],
  'treeshaking pass 24': [ 117.04100000858307, 2977256, 791887464 ],
  'treeshaking pass 25': [ 117.37379997968674, 2252688, 794140216 ],
  'treeshaking pass 26': [ 118.58410000801086, -14342024, 779798256 ],
  '- plugin 17 (node-externals) - buildEnd': [ 2.2318000197410583, 366408, 780239480 ],
  '- plugin 19 (commonjs) - buildEnd': [ 0.06509995460510254, 336, 780240192 ]
}
```
```

### PR DESCRIPTION
**Pull request by markthree**
### 🔗 Linked issue

close #2367 

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation, readme, or JSdoc annotations)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [x] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by pi0** [comment]
implementation note: https://github.com/unjs/nitro/issues/2367#issuecomment-2059709541

File: src/rollup/plugins/externals-legacy.ts [hunk 1]
```diff
@@ -139,13 +139,13 @@ export function externals(opts: NodeExternalsOptions): Plugin {
         // Absolute path, we are not sure about subpath to generate import statement
         // Guess as main subpath export
         const packageEntry = await _resolve(pkgName).catch(() => null);
-        if (packageEntry !== originalId) {
+        if (packageEntry !== id) {
```
Comment (pi0) [inline src/rollup/plugins/externals-legacy.ts:142]: externals-legacy is an snapshot for old behavior let's not touch it 

```suggestion
        if (packageEntry !== originalId) {
```

File: src/rollup/plugins/externals-legacy.ts [hunk 2]
```diff
@@ -139,13 +139,13 @@ export function externals(opts: NodeExternalsOptions): Plugin {
...
           // Guess subpathexport
           const guessedSubpath = pkgName + subpath.replace(/\.[a-z]+$/, "");
           const resolvedGuess = await _resolve(guessedSubpath).catch(
             () => null
           );
-          if (resolvedGuess === originalId) {
+          if (resolvedGuess === id) {
```
Comment (pi0) [inline src/rollup/plugins/externals-legacy.ts:148]:
```suggestion
          if (resolvedGuess === originalId) {
```

**Review by pi0 — APPROVED** [review]
Thanks ❤️
