### PR TITLE
fix: split cookie headers 

### LINKED ISSUE #988: Set Cookie merged into one header (Cloudflare Workers)
### Environment

Cloudflare Workers entry

### Reproduction

Make proxy which sets more than 2 cookies 

### Describe the bug

When you set cookies all you cookies merged into one header, while it’s not allowed by RFC. You need to pass one header per cookie 

### Additional context

I gonna open PR and fix it, I will link it 

### Logs

_No response_

### PR DESCRIPTION
**Pull request by Hebilicious**
- feat: handler cookie headers for Response
- chore: flag unhandled cookies

### 🔗 Linked issue

Closes https://github.com/unjs/nitro/pull/989
Fix #988 

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [x] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

Continuing the work done by @oleghalin and applying it more generally to every presets that needs it.
Note that the culprit for this would be `unenv`, but fixing this in Nitro allows us to not add any dependency to `unenv`.

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by pi0** [comment]
Thanks. I think we can add fix to a wrapper of localFetch util directly so that entries using it already have fix

**Comment by Hebilicious** [comment]
> Thanks. I think we can add fix to a wrapper of localFetch util directly so that entries using it already have fix

We can do it like this  :
```ts
  function normalizedHeaders(fetch: typeof globalThis.fetch) {
    return async (...args: Parameters<typeof fetch>) => {
      const r = await fetch(...args);
      return new Response(r.body, {
        headers: normalizeOutgoingHeaders(r.headers),
        status: r.status,
        statusText: r.statusText,
      });
    };
  }

  // Create local fetch callers
  const localCall = createCall(toNodeListener(h3App) as any);
  const localFetch = normalizedHeaders(
    createLocalFetch(localCall, globalThis.fetch)
  );
  ```
I'm worried about the possible impact of changing `$fetch` for Nuxt, or something else besides the preset runtimes.
If the goal is to DRY we can add a `localNormalizedHeadersFetch` and call this in the presets.
I think I'll let you decide.

**Comment by pi0** [comment]
Yes, i still think wrapper method would be better idea.

**Comment by Hebilicious** [comment]
Is there any reason why cloudflare, lagon, denos, netlify-edge, service worker and vercel-edge presets are using localCall ? They are all returning a Response.

**Comment by pi0** [comment]
> Is there any reason why cloudflare, lagon, denos, netlify-edge, service worker and vercel-edge presets are using localCall ? They are all returning a Response.

They need to be upgraded feel free to include fix in same PR (basically i made that refactor back in time for other presets to prepare for this unified fix :D)

File: src/runtime/app.ts [hunk 1]
```diff
@@ -120,6 +125,7 @@ function createNitroApp(): NitroApp {
     router,
     localCall,
     localFetch,
+    localFetchWithNormalizedHeaders,
```
Comment (pi0) [inline src/runtime/app.ts:128]: We should directly apply patch to `localFetch` if for (any) reason you think we need an escape hatch to disable the normalization of cookie header, it can be a custom fetch option however i think we should not need it

File: src/runtime/entries/stormkit.ts [hunk 2]
```diff
@@ -34,6 +34,7 @@ export const handler: Handler<StormkitEvent, StormkitResult> = async function (
     body: event.body,
   });
 
+  // @todo handle cookies
```
Comment (pi0) [inline src/runtime/entries/stormkit.ts:37]: We probably can remove this todos. `normalizeOutgoingHeaders` should be able to fix this

File: src/runtime/app.ts (hunk 1 above)
Comment (Hebilicious) [reply src/runtime/app.ts:128]: We are no longer returning the full Response, but a subset of it that contains body, headers, status and statusText. 
This matters for $fetch usage. 
Should we try to return everything and change localFetch itself.

Comment (Hebilicious) [reply src/runtime/app.ts:128]: Actually nvm I think it should work

Comment (pi0) [reply src/runtime/app.ts:128]: We can make a internal `_localFetch` variable only being passed to `createFetch` but i guess if standard is to split cookies, it is also nice to be applied to subsequent local `$fetch` calls..

What is more than body, headers, status, statusText available in a Response object?

File: src/runtime/entries/stormkit.ts (hunk 2 above)
Comment (Hebilicious) [reply src/runtime/entries/stormkit.ts:37]: I believe stormkit just wraps lambda so the cookies needs to be handled like in the `aws-lambda` preset

File: src/runtime/utils.ts [hunk 3]
```diff
@@ -100,3 +102,35 @@ export function trapUnhandledNodeErrors() {
...
+        outgoingHeaders.append("set-cookie", cookie);
+      }
+    } else {
+      outgoingHeaders.set(name, joinIfArray(header));
+    }
+  }
+  return outgoingHeaders;
+}
+
+export function withNormalizedHeaders(fetch: typeof globalThis.fetch) {
```
Comment (pi0) [inline src/runtime/utils.ts:127]: This as a generic utility might be confusing to be seen (and named like this) here. Do you mind to move it inline to `app.ts`? 🙏🏼 (also we might end up moving fix finally to the unenv)

File: src/runtime/entries/stormkit.ts (hunk 2 above)
Comment (Hebilicious) [reply src/runtime/entries/stormkit.ts:37]: This needs to be done in netlify-lambda too

Comment (pi0) [reply src/runtime/entries/stormkit.ts:37]: Sure if it is an easy thing to do we can make this PR a fix to normalize cookies for all presets...

**Comment by Hebilicious** [comment]
@danielroe tagging you for the Azure changes

**Comment by pi0** [comment]
Added some refactors and tests. While making tests discovered some issues. Netlify is fixed but we have Node (https://github.com/unjs/nitro/issues/1462) and Bun (https://github.com/unjs/nitro/issues/1461) to be fixed.

Probably on nitro-deploys with edge channel we can E2E test better on tests to.

**Review by pi0 — APPROVED** [review]
