### PR TITLE
fix: exclude internal `/_*`, `/api/_*` routes from NitroFetchReqeust type

### LINKED ISSUE #231: fix: exclude all `/_*` and `/api/_*` routes from `NitroFetchRequest` type
### Environment

- Node version: 16.13.0
- Nitro version: 0.4.4

### Reproduction

```
git clone https://github.com/unjs/nitro.git
cd nitro
pnpm install
pnpm dev
```
```ts
// after .nitro folder is created, go to playground, create a `_internalRoute.ts` route.
then use $fetch in other file:
$fetch(`/** typescript should not show type hints with '/_internalRoute' */`)  
```

### Describe the bug

type `NitroFetchRequest` should exclude all `/_*` and `/api/_*` routes as they are for internal use and should not show type hints/auto-complete to end users

### Additional context

_No response_

### Logs

_No response_

corresponding PR: #232

### PR DESCRIPTION
**Pull request by didavid61202**
### 🔗 Linked issue

fix #231

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

type `NitroFetchRequest` should exclude all `/_*` and `/api/_*` routes as they are for internal use and should not show type hints/auto-complete to end users.

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

File: src/types/fetch.ts [hunk 1]
```diff
@@ -3,7 +3,7 @@ import type { FetchRequest, FetchOptions, FetchResponse } from 'ohmyfetch'
 // An interface to extend in a local project
 export interface InternalApi { }
 
-export type NitroFetchRequest = keyof InternalApi | Exclude<FetchRequest, string> | string & {}
+export type NitroFetchRequest = Exclude<keyof InternalApi | Exclude<FetchRequest, string> | string & {}, `/_${string}`|`/api/_${string}`>
```
Comment (pi0) [inline src/types/fetch.ts:6]: Shall we only exclude from `keyof InternalApi`?

```suggestion
export type NitroFetchRequest = Exclude<keyof InternalApi, `/_${string}`|`/api/_${string}`> | Exclude<FetchRequest, string> | string & {}
```

Comment (didavid61202) [reply src/types/fetch.ts]: Yes, my mistake, that will be better 👍
