### PR TITLE
fix(dev):`remoteAddress` might be undefined for `x-forwarded-for`

### LINKED ISSUE #2197: x-forwared-for error on stackblitz
### Environment

"nuxt": "^3.10.3",
"nitro": "2.9.0"

### Reproduction

https://stackblitz.com/edit/github-jnmnbt?file=README.md

### Describe the bug

A new Nuxt Starter on Stackblitz via [nuxt.new](nuxt.new) leads to an error - nothing will be rendered. (undefined - x-forwared-for)

```
 ERROR  [uncaughtException] Invalid value "undefined" for header "x-forwarded-for"  
```

Downgrading `nitropack` to 2.8.1 fixes the issue.

### Additional context

_No response_

### Logs

```sh
ERROR  [uncaughtException] Invalid value "undefined" for header "x-forwarded-for"                        10:57:09

  at __node_internal_ (https://githubjnmnbt-om4n.w-credentialless-staticblitz.com/blitz.c9a8a620.js:36:5406)
  at new <anonymous> (https://githubjnmnbt-om4n.w-credentialless-staticblitz.com/blitz.c9a8a620.js:36:4168)
  at __node_internal_ (https://githubjnmnbt-om4n.w-credentialless-staticblitz.com/blitz.c9a8a620.js:184:8336)
  at OutgoingMessage.appendHeader (https://githubjnmnbt-om4n.w-credentialless-staticblitz.com/blitz.c9a8a620.js:184:8963)
  at ProxyServer.eval (node_modules/nitropack/dist/chunks/server.mjs:342:16)
  at EventEmitter.emit (https://githubjnmnbt-om4n.w-credentialless-staticblitz.com/blitz.c9a8a620.js:42:9202)
  at ClientRequest.eval (node_modules/httpxy/dist/index.mjs:272:16)
  at EventEmitter.emit (https://githubjnmnbt-om4n.w-credentialless-staticblitz.com/blitz.c9a8a620.js:42:9202)
  at https://githubjnmnbt-om4n.w-credentialless-staticblitz.com/blitz.c9a8a620.js:252:11492
  at onSocketNT (https://githubjnmnbt-om4n.w-credentialless-staticblitz.com/blitz.c9a8a620.js:252:11509)
```
```

### PR DESCRIPTION
**Pull request by manniL**
### 🔗 Linked issue

Resolves #2197 

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation, readme, or JSdoc annotations)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📝 Checklist

- [ ] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

File: src/dev/server.ts [hunk 1]
```diff
@@ -197,7 +197,10 @@ export function createDevServer(nitro: Nitro): NitroDevServer {
   proxy.proxy.on("proxyReq", (proxyReq, req) => {
     // TODO: Use httpxy to set these headers
     if (!proxyReq.hasHeader("x-forwarded-for")) {
-      proxyReq.appendHeader("x-forwarded-for", req.socket.remoteAddress);
+      const address = req.socket.remoteAddress;
+      if (address) {
```
Comment (pi0) [inline src/dev/server.ts:201]:
```suggestion
      // #2197
      if (address) {
```

**Review by pi0 — APPROVED** [review]
Thanks!
